### ISSUE TITLE
psicode.org is redirecting to a porn site

### ISSUE THREAD

**Issue by dkoes** [psi4/psi4#342]
I assume you already know, but you might want to update/disable the links on github at least.

**Comment by ryanmrichard** [comment]
It's fine on my computer.  Can anyone else confirm?

**Comment by jturney** [comment]
It's fine on mine, too.

**Comment by andysim** [comment]
Not seeing any problems here either.  Was it one particular link on GH that’s bad?

**Comment by dkoes** [comment]
It's possible the problem is with the DNS servers.  It happens pretty reliably if I google psi4 and click on the top hit.  It happens on my desktop and mobile, including if I disconnect from the wireless and use T-Mobile's network.

**Comment by jturney** [comment]
Whoa, yeah, just googled psi4 and got hit with it.

**Comment by loriab** [comment]
Just clicked through all the links on the README.md page, and they all seem alright. Thanks for the warning that this is a problem.

**Comment by ryanmrichard** [comment]
Me too.

**Comment by bennybp** [comment]
Also confirming here, also on yahoo/bing. Can someone make sure we still have control of the domain name? Whois is still showing it registered to David Sherrill, and it still shows it going to godaddy, but it won't hurt to make sure

**Comment by lothian** [comment]
I'm not observing any of this behavior, so just to clarify: does anyone
actually get this "redirection" when you enter "psicode.org" on your URL
bar?  Or do you just get this when you search for PSI4 on
Google/Yahoo/Bing?  NB: When I put "PSI4" in those search engines, I get
only our correct site for the first page of hits (except for the Wikipedia
page on "Psi4 Aurigae").  And yes, we have control of the domain via
godaddy.com.

-TDC

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by bennybp** [comment]
Not when entered directly (at least I haven't observed it). Only when going through google or yahoo/bing, not through duckduckgo (even using google through duckduckgo). The correct site is listed, but clicking on it causes a redirect.

Not sure about a DNS issue, though. I can't see any connection between the redirect location and psicode.org (different hosting, etc).

**Comment by amjames** [comment]
I am also being re-directed from search engines. The top site shows psicode.org but will redirect if I click on it. Typing psicode.org into a browser will bring me to the correct page, but I am noticing that the “manual” link is not working properly.

I have that bookmarked and I wanted to see if that would redirect. It does not re-direct but none of the CSS elements associated with the manual are being loaded properly. I see the manual appearing as plain HTML. The same thing happens if I navigate to the manual from the psicode.org homepage.

The console in chrome and safari are showing 404 errors for js and css:

http://psicode.org/psi4manual/master/_static/psi4.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://psicode.org/psi4manual/master/_static/pygments.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://psicode.org/psi4manual/master/_static/doctools.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://psicode.org/psi4manual/master/_static/underscore.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://psicode.org/psi4manual/master/_static/jquery.cookie.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://psicode.org/psi4manual/master/_static/jquery.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://psicode.org/psi4manual/master/_static/toggle_sections.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://psicode.org/psi4manual/master/_static/toggle_codeprompt.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://psicode.org/psi4manual/master/_static/toggle_sidebar.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://psicode.org/psi4manual/master/_images/psi4banner.png Failed to load resource: the server responded with a status of 404 (Not Found)
index.html:368 Uncaught ReferenceError: $ is not defined
http://psicode.org/psi4manual/master/_static/favicon-psi4.ico Failed to load resource: the server responded with a status of 404 (Not Found)
http://psicode.org/psi4manual/master/_static/pygments.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://psicode.org/psi4manual/master/_static/psi4.css Failed to load resource: the server responded with a status of 404 (Not Found)
Is anyone else seeing this problem? Possibly related?



—AJ

On April 14, 2016 at 11:37:37 AM, T. Daniel Crawford (notifications@github.com) wrote:

I'm not observing any of this behavior, so just to clarify: does anyone
actually get this "redirection" when you enter "psicode.org" on your URL
bar? Or do you just get this when you search for PSI4 on
Google/Yahoo/Bing? NB: When I put "PSI4" in those search engines, I get
only our correct site for the first page of hits (except for the Wikipedia
page on "Psi4 Aurigae"). And yes, we have control of the domain via
godaddy.com.

-TDC

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by CDSherrill** [comment]
If I do a Yahoo search, I get redirected if I click the link to
www.psicode.org (top hit), www.psicode.org/labs.php (2nd hit), or
github.com/psi4/psi4 (3rd hit).

It is really weird that github is also being intercepted.  I could imagine
how our DNS might have been hijacked, etc., but not how the github link
could have been...

David

**Comment by dkoes** [comment]
The direct link was initially problematic for me, but no longer.  I suspect a DNS server got compromised, it was taken down, and now you're dealing with having to wait for the malicious information to clear out of all the various caches...

**Comment by bennybp** [comment]
I'm suspecting that also. One odd thing is that it only did it for me (and others) from a search engine. It's hijacking based on the referer in the header (no idea if this is common).

compare:

    wget --referer www.google.com psicode.org

vs

    wget psicode.org

The first will download an html document that is just a redirect. The second gets me the real psicode.org

**Comment by dkoes** [comment]
That could be a clever way to delay site owners from realizing what happened to them.. who googles for their own URL?

**Comment by bennybp** [comment]
Actually, if what I said was correct, that's not quite DNS hijacking. It's still resolving to the correct IP, but downloading a different document based on referer. This would point to a godaddy server hijacking (I would think)

**Comment by hokru** [comment]
This sort of soft hijacking is pretty common. After resolving the issue make sure google/bing did not blacklist your domain.

**Comment by lothian** [comment]
How do we deal with this?  Do we just wait, or is there something we have
to resolve ourselves?

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by bennybp** [comment]
Since it's still redirecting for me, GoDaddy support is probably the best bet

**Comment by CDSherrill** [comment]
Yeah, that seems reasonable.  Maybe Daniel can get them on the case.  I'm
still confused about how our github page also got hijacked, though, since
that is a totally different domain.  Were we specifically targeted?

**Comment by bennybp** [comment]
The github links (when clicking on them from a search) seem to work ok. It's the links to psicode.org

The two main possibilities are:

  1.) Hacked php file on psicode.org. (Involves multiple php files. The link to labs.php also redirects)

  2.) Hacked godaddy server itself, causing redirects

I see other domains on that server have been compromised. That doesn't narrow the problem down at all, and it looks like the others are slightly different. Some have already been marked as malicious by google. (https://www.google.com/#q=scottwandersonphotography.com)

**Comment by bennybp** [comment]
Fixed, i think, at least for now. Addresses were being rewritten via the .htaccess file, but only for certain referers.

My guess is the html directory was group writable. It also looks lime they changed the permissions on some directories to 704, which is odd. They were maybe covering up their tracks.

On April 14, 2016 6:26:56 PM EDT, David Sherrill <notifications@github.com> wrote:
>Yeah, that seems reasonable.  Maybe Daniel can get them on the case. 
>I'm
>still confused about how our github page also got hijacked, though,
>since
>that is a totally different domain.  Were we specifically targeted?
>
>On Thursday, April 14, 2016, Ben Pritchard <notifications@github.com>
>wrote:
>
>> Since it's still redirecting for me, GoDaddy support is probably the
>best
>> bet
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/psi4/psi4/issues/342#issuecomment-210157786>
>>
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/psi4/psi4/issues/342#issuecomment-210184446

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andysim** [comment]
Great work tracking that one down, @bennybp et al. and thanks for the heads-up, @dkoes.  Does anybody know why the CSS elements are fubared in the manual?  The issues mentioned by @amjames still persist - perhaps it's a result of those modified directory permissions?

**Comment by lothian** [comment]
Well done, Ben!

Regarding the manual, I note that the psi4manual/master/_static
subdirectory, where the css files should reside, is missing.  @loriab, is
that automatically generated?

-TDC

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by loriab** [comment]
Yes, `_static` is auto-generated and contains the js, css, and png files. I just triggered an extra build, so we'll see if it heals w/i a couple hours.

**Comment by dgasmith** [comment]
Looks like we do not have any curious redirects and the CSS has been reapplied correctly. Closing this, but please let us know if this issue happens again.
