### ISSUE TITLE
orientation, cartesian, and props2

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#782]
https://github.com/psi4/psi4/pull/760/files#diff-aac3b6c47032ba056103b4f355643ca7R3113 makes a lot of sense and eliminates a pit that's easy to fall into. But need to revisit its impact on properties of charged molecules.

Basically, props2 is currently broken, and need to figure out if the recent PR was too aggressive in `no_reorient`ing or if `props2` has been falling into the aforementioned pit all along.

**Comment by loriab** [comment]
w/o reinvestigating, this is my memory of what's going on:

props2 is a Cartesian-with-variable geometry (y-coord gets updated in a loop) with _no explicit_ freeze com/orient. System is a cation so origin of *poles matters. Test ref values are computed at COM. For a long time this was fine b/c in the absence of user forbidding it, molecule was moved to COM & std orientation and computed==expected.

But there's a deep pit that both users and developers can fall into wrt scanning over coordinates of a Cartesian system -- values you're updating aren't in same coord sys as values being specified. Results can be jarring. So DGAS fixed with https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/molecule.cc#L3110-L3117 . This fills the pitfall, but now the props2 case doesn't get moved to COM, so computed != expected. That is, until psi4/psi4#808 where we explictly instruct moving to COM so that test passes again.

Naturally, a Z-Mat molecule would always go to COM and wouldn't have this distinction.

This is all perfectly logical. Trouble is consistency btwn Cart/ZMat and what users will be least confused by.

**Comment by dgasmith** [comment]
Im still not completely sure that there is a way to bridge the two. Ultimately the modification in-place leads to quite a few errors; however, the Psithon API make the in-place a logical operation.

It would be better to do something like:
```
new_mol = molecule.update({"var1": 5, "var2": 6})
```
or something similar. Getting that across in something like Psithon would be difficult I think.

**Comment by CDSherrill** [comment]
Ok thanks for the summary.  I agree the current behavior is logical, and
also that there is an inconsistency between Zmat and Cartesians that could
confuse a user.  I am very happy there is a little warning printed by the
code if the user is updating the Cartesian coordinates.  Perhaps that
warning could be updated to say something like "(multipole moments of
charged molecules may be affected)" or something?  And/or a sentence or two
in whatever section of the manual might cover something like this?

I also recommend expanding the comment in the props2/input.dat from "#
Force COM for pole computation" to the more detailed "# Force COM
translation so multipoles of charged molecule will match reference values"

**Comment by loriab** [comment]
closed by psi4/psi4#808
