### ISSUE TITLE
ValidationError: Unrecognized point group bits: 96

### ISSUE THREAD

**Issue by j3mdamas** [psi4/psi4#948]
Hi,

@raimis and I are working with a development version of psi4. I installed a fresh conda directory (python 3.6) where I ran `conda install psi4=1.2a1.dev611 -c psi4/label/dev -c psi4`. Here's what's installed:

```
-bash-4.2$ conda list
# packages in environment at /home/damasj02/software/psi4dev:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0
attrs                     17.4.0                   py36_0
ca-certificates           2018.03.07                    0
certifi                   2018.1.18                py36_0
cffi                      1.11.4           py36h9745a5d_0
chardet                   3.0.4            py36h0f667ec_1
chemps2                   1.8.4                         0    psi4/label/dev
cloog                     0.18.0                        0
conda                     4.4.10                   py36_0
conda-env                 2.6.0                h36134e3_1
cryptography              2.1.4            py36hd09be54_0
dkh                       1.2                           1    psi4/label/dev
erd                       3.0.6                         1    psi4/label/dev
gcc-5                     5.2.0                         1    psi4
gcc-5-mp                  5.2.0                         0    psi4
gdma                      2.2.6                         3    psi4/label/dev
gmp                       6.1.2                h6c8ec71_1
hdf5                      1.8.17                        2
idna                      2.6              py36h82fb2a8_1
intel-openmp              2018.0.0                      8
isl                       0.12.2                        0
libedit                   3.1                  heed3624_0
libefp                    1.5b1                         0    psi4/label/dev
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 7.2.0                h7cc24e2_2
libgfortran-ng            7.2.0                hdf63c60_3
libint                    1.2.1                         1    psi4/label/dev
libstdcxx-ng              7.2.0                h7a57d05_2
libxc                     3.0.0                         6    psi4/label/dev
mkl                       2018.0.2                      1
mkl_fft                   1.0.1            py36h3010b51_0
mkl_random                1.0.1            py36h629b387_0
more-itertools            4.1.0                    py36_0
mpc                       1.0.1                         0
mpfr                      3.1.2                         0
ncurses                   6.0                  h9df7e31_2
numpy                     1.14.2           py36hdbf6ddf_1
openssl                   1.0.2o               h20670df_0
pcmsolver                 1.1.10                   py36_1    psi4/label/dev
pip                       9.0.1            py36h6c6f9ce_4
pluggy                    0.6.0            py36hb689045_0
psi4                      1.2a1.dev611+8fe3513          py36_0    psi4/label/dev
psi4-lt-mp                1.2a1.dev3               py36_0    psi4/label/dev
py                        1.5.3                    py36_0
pycosat                   0.6.3            py36h0a5515d_0
pycparser                 2.18             py36hf9f622e_1
pyopenssl                 17.5.0           py36h20ba746_0
pysocks                   1.6.7            py36hd97a5b1_1
pytest                    3.5.0                    py36_0
python                    3.6.4                hc3d631a_1
readline                  7.0                  ha6073c6_4
requests                  2.18.4           py36he2e5f8d_1
ruamel_yaml               0.15.35          py36h14c3975_1
setuptools                38.4.0                   py36_0
simint                    0.7                           0    psi4
six                       1.11.0           py36h372c433_1
sqlite                    3.22.0               h1bed415_0
tk                        8.6.7                hc745277_3
urllib3                   1.22             py36hbe7ace6_0
wheel                     0.30.0           py36hfd4bba0_1
xz                        5.2.3                h55aa19d_2
yaml                      0.1.7                had09818_2
zlib                      1.2.11               ha838bed_2
```

Our input is:

```
set_num_threads(4)
set_memory('16000 MB')

set { scf_mem_safety_factor 0.7 }

set { reference rks }
set { basis 6-311++G** }

molecule MOL {
    1 1
    noreorient
    nocom
    symmetry c1
    C    0.000000   0.000000  -0.170000
    C    0.007000   1.210000   0.523000
    C    0.000000   1.205000   1.904000
    C    0.000000   0.000000   2.592000
    C    0.000000  -1.205000   1.904000
    C   -0.007000  -1.210000   0.523000
    C    0.000000   0.000000  -1.643000
    H   -0.019000   2.146000  -0.006000
    H   -0.011000   2.134000   2.442000
    H    0.000000   0.000000   3.666000
    H    0.011000  -2.134000   2.442000
    H    0.019000  -2.146000  -0.006000
    N   -0.741000  -0.864000  -2.296000
    N    0.741000   0.864000  -2.296000
    H    0.721000   0.947000  -3.291000
    H    1.404000   1.427000  -1.808000
    H   -1.404000  -1.427000  -1.808000
    H   -0.721000  -0.947000  -3.291000
}

set optking { dynamic_level = 1
 geom_maxiter = 250
 print_trajectory_xyz_file = True }

set { scf_type direct }
energy, wfn = optimize('SCF', dft_functional='wB97X-D', dertype='gradient', return_wfn=True)

import os
os.chdir(os.environ['HTMD_PSI4_WORKDIR'])

oeprop(wfn, 'DIPOLE', 'QUADRUPOLE', 'MULLIKEN_CHARGES')

with open('psi4out.xyz', 'w') as f:
    f.write('18 ' )
    f.write('%.12f\n' % energy)
    f.write(MOL.save_string_xyz())
```

This errors with:

```
Traceback (most recent call last):
  File "/home/damasj02/software/psi4dev/bin/psi4", line 260, in <module>
    exec(content)
  File "<string>", line 55, in <module>
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/driver.py", line 1054, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/driver.py", line 606, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/procrouting/proc.py", line 2051, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/procrouting/proc.py", line 1989, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/procrouting/proc.py", line 1279, in scf_helper
    base_wfn = core.Wavefunction.build(scf_molecule, core.get_global_option('BASIS'))
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/p4util/python_helpers.py", line 103, in pybuild_wavefunction
    basis = core.BasisSet.build(mol, "ORBITAL", basis)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/p4util/python_helpers.py", line 68, in pybuild_basis
    key, resolved_target, fitrole, other, return_atomlist=return_atomlist)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 661, in pyconstruct
    return_atomlist=return_atomlist)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 877, in construct
    oneatombasis = BasisSet(basisset, at)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 143, in __init__
    self.constructor_basisset_center(*args)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 412, in constructor_basisset_center
    self.molecule.update_geometry()
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/qcdb/libmintsmolecule.py", line 1604, in update_geometry
    self.set_point_group(self.find_point_group())
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/qcdb/libmintsmolecule.py", line 2432, in find_point_group
    pg = self.find_highest_point_group(tol)  # D2h subgroup
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/qcdb/libmintsmolecule.py", line 2532, in find_highest_point_group
    return PointGroup(pg_bits)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/qcdb/libmintspointgrp.py", line 1533, in __init__
    self.constructor_bits(*args)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/qcdb/libmintspointgrp.py", line 1576, in constructor_bits
    self.symb = self.bits_to_basic_name(self.PYbits)
  File "/home/damasj02/software/psi4dev/lib//python3.6/site-packages/psi4/driver/qcdb/libmintspointgrp.py", line 1754, in bits_to_basic_name
    raise ValidationError('Unrecognized point group bits: %d\n' % (bits))

ValidationError: Unrecognized point group bits: 96
```

If I switch to B3LYP functional, there's no problem. And we're also able to run it on another site (different resources). Maybe we're missing some installation or the local machine libraries are not the right versions? I also paste here an `ldd` of the `core.so`.

```
        linux-vdso.so.1 =>  (0x00007ffddc916000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ac921db4000)
        libc.so.6 => /lib64/libc.so.6 (0x00002ac921fd0000)
        libpcm.so.1 => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libpcm.so.1 (0x00002ac922391000)
        libxc.so => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libxc.so (0x00002ac928dfa000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002ac92920a000)
        libgdma.so => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libgdma.so (0x00002ac92940e000)
        libderiv.so => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libderiv.so (0x00002ac92987b000)
        libint.so => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libint.so (0x00002ac92d840000)
        libdkh.so => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libdkh.so (0x00002ac92ed0e000)
        liberd.so => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../liberd.so (0x00002ac92f063000)
        libsimint.so => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libsimint.so (0x00002ac92f950000)
        libefp.so => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libefp.so (0x00002ac931f4c000)
        libmkl_rt.so => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libmkl_rt.so (0x00002ac9321cc000)
        libiomp5.so => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libiomp5.so (0x00002ac932849000)
        libchemps2.so.2 => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libchemps2.so.2 (0x00002ac932bed000)
        /lib64/ld-linux-x86-64.so.2 (0x00002ac91eb2a000)
        libz.so.1 => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../.././libz.so.1 (0x00002ac933435000)
        libm.so.6 => /lib64/libm.so.6 (0x00002ac93364c000)
        libgcc_s.so.1 => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../../libgcc_s.so.1 (0x00002ac93394e000)
        librt.so.1 => /lib64/librt.so.1 (0x00002ac933b64000)
        libhdf5.so.10 => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../.././libhdf5.so.10 (0x00002ac933d6c000)
        libhdf5_hl.so.10 => /home/damasj02/software/psi4dev/lib/python3.6/site-packages/psi4/../../.././libhdf5_hl.so.10 (0x00002ac93424f000)
```

Thanks!
João

**Comment by loriab** [comment]
Well, good news is that the functional and the psi version are irrelevant. It's purely a particular geometry that you hit that's confusing the symmetry detection. And only when not shifted to center-of-mass. Never seen that error before, so will definitely investigate. Below is minimal example.

BTW, `1.2a1.dev600` is still 300-400 commits behind master, due to my conda negligence. If I can get #946 in, I'll have a minimal _new_ conda build on the `-c psi4/label/agg` subchannel that actually uses the `-ng`/gcc72 compilers.

```
molecule MOL {
    1 1
    nocom  # toggle for disaster
    C            0.000000000445    -0.000000002634    -0.176009819382
    C            0.017055492504     1.213674219316     0.519005187104
    C            0.010905297833     1.207533611621     1.904879649273
    C            0.000000001371    -0.000000001015     2.595491320593
    C           -0.010905296809    -1.207533610178     1.904879653967
    C           -0.017055492743    -1.213674218642     0.519005186244
    C            0.000000000685    -0.000000001418    -1.643506768663
    H           -0.011074063554     2.157895826255    -0.014254560550
    H            0.006037200834     2.144998257605     2.447030976059
    H            0.000000002397     0.000000004130     3.679031777447
    H           -0.006037200687    -2.144998259786     2.447030974663
    H            0.011074059226    -2.157895829902    -0.014254553860
    N           -0.738518375832    -0.879256115198    -2.298061241871
    N            0.738518376065     0.879256115454    -2.298061238276
    H            0.714314308196     0.973365270982    -3.302615035270
    H            1.398512102453     1.450008704958    -1.792988230964
    H           -1.398512105220    -1.450008704099    -1.792988237236
    H           -0.714314307164    -0.973365267449    -3.302615039280

}

energy = energy('B3lyp/cc-pvdz')
```

**Comment by jturney** [comment]
Oh wow, I haven't experienced this error before. It detected the xz- and yz- mirror plane and nothing else. It should probably gracefully report the issue and then find a point group that best matches it.

Even though you told Psi4 to use C1 symmetry it still attempts to detect the highest point group for reporting purposes.

I'll see what I can do to fix this.

**Comment by j3mdamas** [comment]
Thanks a lot for the feedback!

I guess that for now I'll micro-wiggle around my initial coordinates a bit and that should fix it, right?

**Comment by loriab** [comment]
It hits the troublesome geometry a couple optimization iterations in, so not guaranteed. But given that this error hasn't popped up for 10 years, micro-wiggle is a good bet.

btw, `conda install psi4 -c psi4/label/agg` will get you a working `-ng`-compiler package at the moment. Though that's my sandbox channel and so the latest package mayn't always be working.

**Comment by j3mdamas** [comment]
Thanks @loriab!

**Comment by loriab** [comment]
Still broken; no spontaneous healing after molecule-handling changes.

**Comment by j3mdamas** [comment]
HI @loriab,

I'm still having this issue with psi 1.2 (the released, not the dev one)

It's quite erratic - sometimes it works, sometimes it doesn't.
I was trying to do some reproducible tests, but I couldn't in the end. I suspect the size of the path to the file is somehow relevant, but I really couldn't prove it with those tests

**Comment by JonathonMisiewicz** [comment]
Is the "it" you're trying the original input file you posted, or the one that Lori posted?

Your input file may or may not demonstrate the problem. Noise in the energy single points leads to noise in the computed gradient leads to noise in the optimization step leads to noise in whether or not you get a problematic geometry. Lori's input file should reproduce the bug 100% of the time.

I've been exploring Psi's symmetry handling for an unrelated issue, and it looks like Psi's symmetry detection assumes the symmetry operations can be oriented along the x-, y-, z- axes. I'm not surprised to see problems with symmetry detection if you don't let Psi center-of-mass-adjust the molecule. The symmetry elements would need to be translated in space.

**Comment by j3mdamas** [comment]
I apologize, maybe I'm fiddling with something different that leads to the same error message. Perhaps it's better to keep the 100% reproducible case. My point was that it was still happening, even with psi 1.2 non-dev.

**Comment by loriab** [comment]
I completely agree that this is still an active issue (and an edge case at that). Good news is it's at the single class level. Bad news is unlikely to get tackled unless as a side fix of other symmetry investigations (as Jonathon is doing) or Jet gets bored. Are you hitting it frequently in your work or is it a niggling side issue?

**Comment by j3mdamas** [comment]
Niggling side issue, so don't worry. If it becomes frequent, I'll report.

**Comment by JonathonMisiewicz** [comment]
Francesco found another example today... I'll look into this for 1.7, but I am not touching the Molecule class until after DDD is in.

**Comment by loriab** [comment]
> Francesco found another example today... I'll look into this for 1.7, but I am not touching the Molecule class until after DDD is in.

Molecule escapes the DDD upheaval, but +1 for 1.7.

**Comment by Awallace3** [comment]
Here is another example of this error.

`memory 2 GB
molecule {
8       0.0000079789    0.0000000002    3.3734612294
1       -0.7693027984   -0.0000000004   3.9669401984
1       0.7691761670    -0.0000000031   3.9671249871
}

energy('pbe0/aug-cc-pVDZ')
`

**Comment by susilehtola** [comment]
FWIW Peter Knowles has recently published an open source code for identifying the point group of a molecule https://link.springer.com/article/10.1007/s10910-021-01302-x

**Comment by JonathonMisiewicz** [comment]
Nice.

Does it make a difference that the Knowles code uses the MIT license, whereas we use one of the GNU licenses?

**Comment by susilehtola** [comment]
> Nice.
> 
> Does it make a difference that the Knowles code uses the MIT license, whereas we use one of the GNU licenses?

No. MIT is compatible with LGPL and GPL, see e.g. https://www.gnu.org/licenses/license-list.en.html#Expat

AFAIK the Knowles code base could be included as a subrepo or included in Psi4 without problems.
